import wxdata.open_meteo_api.seasonal_forecasts.ecmwf_daily as ecmwf_seasonal_forecasts_daily
import wxdata.open_meteo_api.seasonal_forecasts.ecmwf_weekly as ecmwf_seasonal_forecasts_weekly
import wxdata.open_meteo_api.seasonal_forecasts.ecmwf_monthly as ecmwf_seasonal_forecasts_monthly