import wxdata.api.open_meteo_api.marine_forecasts.meteo_france as open_meteo_api_meteo_france_marine
import wxdata.api.open_meteo_api.marine_forecasts.dwd as open_meteo_api_dwd_marine
import wxdata.api.open_meteo_api.marine_forecasts.ecmwf as open_meteo_api_ecmwf_marine
import wxdata.api.open_meteo_api.marine_forecasts.noaa as open_meteo_api_noaa_marine