"""
This file hosts the functions that perform various tasks with respect to the file naming and file structure.

(C) Eric J. Drewitz 2025 
"""

import os

def gem_global_file_prefixes(run, date, set):
    
    """
    This function returns a list of file names for the files for all variables and levels of the GEM Global.
    
    Required Arguments:
    
    1) run (String) - The model run time in string format. 
    
    2) date (String) - The date in the form of a string
    
    Optional Arguments: None
    
    Returns
    -------
    
    A list of file prefixes for all variables at all levels in the GEM Global Data    
    """
    set = set.lower()
    
    if set == 'full':

        file_prefixes = [
            f"CMC_glb_ABSV_ISBL_200_latlon.15x.15_{date}{run}",
            f"CMC_glb_ABSV_ISBL_250_latlon.15x.15_{date}{run}",
            f"CMC_glb_ABSV_ISBL_500_latlon.15x.15_{date}{run}",
            f"CMC_glb_ABSV_ISBL_700_latlon.15x.15_{date}{run}",
            f"CMC_glb_ABSV_ISBL_850_latlon.15x.15_{date}{run}",
            f"CMC_glb_ACPCP_SFC_0_latlon.15x.15_{date}{run}",
            f"CMC_glb_ALBDO_SFC_0_latlon.15x.15_{date}{run}",
            f"CMC_glb_CAPE_SFC_0_latlon.15x.15_{date}{run}",
            f"CMC_glb_CIN_SFC_0_latlon.15x.15_{date}{run}",
            f"CMC_glb_CWAT_EATM_0_latlon.15x.15_{date}{run}",
            f"CMC_glb_DEPR_ISBL_1000_latlon.15x.15_{date}{run}",
            f"CMC_glb_DEPR_ISBL_100_latlon.15x.15_{date}{run}",
            f"CMC_glb_DEPR_ISBL_1015_latlon.15x.15_{date}{run}",
            f"CMC_glb_DEPR_ISBL_10_latlon.15x.15_{date}{run}",
            f"CMC_glb_DEPR_ISBL_150_latlon.15x.15_{date}{run}",
            f"CMC_glb_DEPR_ISBL_175_latlon.15x.15_{date}{run}",
            f"CMC_glb_DEPR_ISBL_200_latlon.15x.15_{date}{run}",
            f"CMC_glb_DEPR_ISBL_20_latlon.15x.15_{date}{run}",
            f"CMC_glb_DEPR_ISBL_225_latlon.15x.15_{date}{run}",
            f"CMC_glb_DEPR_ISBL_250_latlon.15x.15_{date}{run}",
            f"CMC_glb_DEPR_ISBL_275_latlon.15x.15_{date}{run}",
            f"CMC_glb_DEPR_ISBL_300_latlon.15x.15_{date}{run}",
            f"CMC_glb_DEPR_ISBL_30_latlon.15x.15_{date}{run}",
            f"CMC_glb_DEPR_ISBL_350_latlon.15x.15_{date}{run}",
            f"CMC_glb_DEPR_ISBL_400_latlon.15x.15_{date}{run}",
            f"CMC_glb_DEPR_ISBL_450_latlon.15x.15_{date}{run}",
            f"CMC_glb_DEPR_ISBL_500_latlon.15x.15_{date}{run}",
            f"CMC_glb_DEPR_ISBL_50_latlon.15x.15_{date}{run}",
            f"CMC_glb_DEPR_ISBL_550_latlon.15x.15_{date}{run}",
            f"CMC_glb_DEPR_ISBL_600_latlon.15x.15_{date}{run}",
            f"CMC_glb_DEPR_ISBL_650_latlon.15x.15_{date}{run}",
            f"CMC_glb_DEPR_ISBL_700_latlon.15x.15_{date}{run}",
            f"CMC_glb_DEPR_ISBL_750_latlon.15x.15_{date}{run}",
            f"CMC_glb_DEPR_ISBL_800_latlon.15x.15_{date}{run}",
            f"CMC_glb_DEPR_ISBL_850_latlon.15x.15_{date}{run}",
            f"CMC_glb_DEPR_ISBL_875_latlon.15x.15_{date}{run}",
            f"CMC_glb_DEPR_ISBL_900_latlon.15x.15_{date}{run}",
            f"CMC_glb_DEPR_ISBL_925_latlon.15x.15_{date}{run}",
            f"CMC_glb_DEPR_ISBL_950_latlon.15x.15_{date}{run}",
            f"CMC_glb_DEPR_ISBL_970_latlon.15x.15_{date}{run}",
            f"CMC_glb_DEPR_ISBL_985_latlon.15x.15_{date}{run}",
            f"CMC_glb_DEPR_TGL_2_latlon.15x.15_{date}{run}",
            f"CMC_glb_DLWRF_SFC_0_latlon.15x.15_{date}{run}",
            f"CMC_glb_DPT_TGL_2_latlon.15x.15_{date}{run}",
            f"CMC_glb_DSWRF_NTAT_0_latlon.15x.15_{date}{run}",
            f"CMC_glb_DSWRF_SFC_0_latlon.15x.15_{date}{run}",
            f"CMC_glb_GUST_MAX_TGL_10_latlon.15x.15_{date}{run}",
            f"CMC_glb_GUST_MIN_TGL_10_latlon.15x.15_{date}{run}",
            f"CMC_glb_GUST_TGL_10_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBL_1000_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBL_100_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBL_1015_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBL_10_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBL_150_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBL_175_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBL_1_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBL_200_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBL_20_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBL_225_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBL_250_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBL_275_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBL_300_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBL_30_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBL_350_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBL_400_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBL_450_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBL_500_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBL_50_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBL_550_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBL_5_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBL_600_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBL_650_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBL_700_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBL_750_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBL_800_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBL_850_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBL_875_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBL_900_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBL_925_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBL_950_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBL_970_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBL_985_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBY_1000-500_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBY_1000-850_latlon.15x.15_{date}{run}",
            f"CMC_glb_HGT_ISBY_850-700_latlon.15x.15_{date}{run}",
            f"CMC_glb_HPBL_SFC_0_latlon.15x.15_{date}{run}",
            f"CMC_glb_Humidex_SFC_0_latlon.15x.15_{date}{run}",
            f"CMC_glb_KX_SFC_0_latlon.15x.15_{date}{run}",
            f"CMC_glb_LHTFL_SFC_0_latlon.15x.15_{date}{run}",
            f"CMC_glb_MU-VT-LI_ISBL_500_latlon.15x.15_{date}{run}",
            f"CMC_glb_NLWRS_SFC_0_latlon.15x.15_{date}{run}",
            f"CMC_glb_NSWRS_SFC_0_latlon.15x.15_{date}{run}",
            f"CMC_glb_O3MixingRatio_Sfc_latlon.15x.15_{date}{run}",
            f"CMC_glb_O3_EAtm_latlon.15x.15_{date}{run}",
            f"CMC_glb_PRES_PVU_1.5_latlon.15x.15_{date}{run}",
            f"CMC_glb_PRES_PVU_1_latlon.15x.15_{date}{run}",
            f"CMC_glb_PRES_PVU_2_latlon.15x.15_{date}{run}",
            f"CMC_glb_PRES_SFC_0_latlon.15x.15_{date}{run}",
            f"CMC_glb_PRMSL_MSL_0_latlon.15x.15_{date}{run}",
            f"CMC_glb_PTYPE_SFC_0_latlon.15x.15_{date}{run}",
            f"CMC_glb_RELV_ISBL_200_latlon.15x.15_{date}{run}",
            f"CMC_glb_RELV_ISBL_250_latlon.15x.15_{date}{run}",
            f"CMC_glb_RELV_ISBL_500_latlon.15x.15_{date}{run}",
            f"CMC_glb_RELV_ISBL_700_latlon.15x.15_{date}{run}",
            f"CMC_glb_RELV_ISBL_850_latlon.15x.15_{date}{run}",
            f"CMC_glb_RH_ISBL_1000_latlon.15x.15_{date}{run}",
            f"CMC_glb_RH_ISBL_100_latlon.15x.15_{date}{run}",
            f"CMC_glb_RH_ISBL_1015_latlon.15x.15_{date}{run}",
            f"CMC_glb_RH_ISBL_10_latlon.15x.15_{date}{run}",
            f"CMC_glb_RH_ISBL_150_latlon.15x.15_{date}{run}",
            f"CMC_glb_RH_ISBL_175_latlon.15x.15_{date}{run}",
            f"CMC_glb_RH_ISBL_200_latlon.15x.15_{date}{run}",
            f"CMC_glb_RH_ISBL_20_latlon.15x.15_{date}{run}",
            f"CMC_glb_RH_ISBL_225_latlon.15x.15_{date}{run}",
            f"CMC_glb_RH_ISBL_250_latlon.15x.15_{date}{run}",
            f"CMC_glb_RH_ISBL_275_latlon.15x.15_{date}{run}",
            f"CMC_glb_RH_ISBL_300_latlon.15x.15_{date}{run}",
            f"CMC_glb_RH_ISBL_30_latlon.15x.15_{date}{run}",
            f"CMC_glb_RH_ISBL_350_latlon.15x.15_{date}{run}",
            f"CMC_glb_RH_ISBL_400_latlon.15x.15_{date}{run}",
            f"CMC_glb_RH_ISBL_450_latlon.15x.15_{date}{run}",
            f"CMC_glb_RH_ISBL_500_latlon.15x.15_{date}{run}",
            f"CMC_glb_RH_ISBL_50_latlon.15x.15_{date}{run}",
            f"CMC_glb_RH_ISBL_550_latlon.15x.15_{date}{run}",
            f"CMC_glb_RH_ISBL_600_latlon.15x.15_{date}{run}",
            f"CMC_glb_RH_ISBL_650_latlon.15x.15_{date}{run}",
            f"CMC_glb_RH_ISBL_700_latlon.15x.15_{date}{run}",
            f"CMC_glb_RH_ISBL_750_latlon.15x.15_{date}{run}",   
            f"CMC_glb_RH_ISBL_800_latlon.15x.15_{date}{run}",   
            f"CMC_glb_RH_ISBL_850_latlon.15x.15_{date}{run}",
            f"CMC_glb_RH_ISBL_875_latlon.15x.15_{date}{run}",
            f"CMC_glb_RH_ISBL_900_latlon.15x.15_{date}{run}",   
            f"CMC_glb_RH_ISBL_925_latlon.15x.15_{date}{run}",   
            f"CMC_glb_RH_ISBL_950_latlon.15x.15_{date}{run}",   
            f"CMC_glb_RH_ISBL_970_latlon.15x.15_{date}{run}",
            f"CMC_glb_RH_ISBL_985_latlon.15x.15_{date}{run}",
            f"CMC_glb_RH_TGL_2_latlon.15x.15_{date}{run}",  
            f"CMC_glb_SDEN_SFC_0_latlon.15x.15_{date}{run}",
            f"CMC_glb_SFCWRO_SFC_0_latlon.15x.15_{date}{run}",
            f"CMC_glb_SHTFL_SFC_0_latlon.15x.15_{date}{run}",
            f"CMC_glb_SHWINX_ISBL_500_latlon.15x.15_{date}{run}",
            f"CMC_glb_SKINT_SFC_0_latlon.15x.15_{date}{run}",
            f"CMC_glb_SNOD_SFC_0_latlon.15x.15_{date}{run}",
            f"CMC_glb_SOILVIC_SFC_0_latlon.15x.15_{date}{run}",
            f"CMC_glb_SOILW_DBLL_100_latlon.15x.15_{date}{run}",
            f"CMC_glb_SOILW_DBLY_10_latlon.15x.15_{date}{run}",
            f"CMC_glb_SPFH_ISBL_1000_latlon.15x.15_{date}{run}",
            f"CMC_glb_SPFH_ISBL_100_latlon.15x.15_{date}{run}",
            f"CMC_glb_SPFH_ISBL_1015_latlon.15x.15_{date}{run}",
            f"CMC_glb_SPFH_ISBL_10_latlon.15x.15_{date}{run}",  
            f"CMC_glb_SPFH_ISBL_150_latlon.15x.15_{date}{run}",
            f"CMC_glb_SPFH_ISBL_175_latlon.15x.15_{date}{run}",
            f"CMC_glb_SPFH_ISBL_1_latlon.15x.15_{date}{run}",   
            f"CMC_glb_SPFH_ISBL_200_latlon.15x.15_{date}{run}",
            f"CMC_glb_SPFH_ISBL_20_latlon.15x.15_{date}{run}",  
            f"CMC_glb_SPFH_ISBL_225_latlon.15x.15_{date}{run}",
            f"CMC_glb_SPFH_ISBL_250_latlon.15x.15_{date}{run}", 
            f"CMC_glb_SPFH_ISBL_275_latlon.15x.15_{date}{run}",
            f"CMC_glb_SPFH_ISBL_300_latlon.15x.15_{date}{run}", 
            f"CMC_glb_SPFH_ISBL_30_latlon.15x.15_{date}{run}",  
            f"CMC_glb_SPFH_ISBL_350_latlon.15x.15_{date}{run}", 
            f"CMC_glb_SPFH_ISBL_400_latlon.15x.15_{date}{run}",
            f"CMC_glb_SPFH_ISBL_450_latlon.15x.15_{date}{run}", 
            f"CMC_glb_SPFH_ISBL_500_latlon.15x.15_{date}{run}",
            f"CMC_glb_SPFH_ISBL_50_latlon.15x.15_{date}{run}",  
            f"CMC_glb_SPFH_ISBL_550_latlon.15x.15_{date}{run}",
            f"CMC_glb_SPFH_ISBL_5_latlon.15x.15_{date}{run}",
            f"CMC_glb_SPFH_ISBL_600_latlon.15x.15_{date}{run}",
            f"CMC_glb_SPFH_ISBL_650_latlon.15x.15_{date}{run}",
            f"CMC_glb_SPFH_ISBL_700_latlon.15x.15_{date}{run}",
            f"CMC_glb_SPFH_ISBL_750_latlon.15x.15_{date}{run}",
            f"CMC_glb_SPFH_ISBL_800_latlon.15x.15_{date}{run}", 
            f"CMC_glb_SPFH_ISBL_850_latlon.15x.15_{date}{run}",
            f"CMC_glb_SPFH_ISBL_875_latlon.15x.15_{date}{run}",
            f"CMC_glb_SPFH_ISBL_900_latlon.15x.15_{date}{run}",
            f"CMC_glb_SPFH_ISBL_925_latlon.15x.15_{date}{run}",
            f"CMC_glb_SPFH_ISBL_950_latlon.15x.15_{date}{run}",
            f"CMC_glb_SPFH_ISBL_970_latlon.15x.15_{date}{run}",
            f"CMC_glb_SPFH_ISBL_985_latlon.15x.15_{date}{run}",
            f"CMC_glb_SPFH_SFC_0_latlon.15x.15_{date}{run}",
            f"CMC_glb_SPFH_TGL_120_latlon.15x.15_{date}{run}",  
            f"CMC_glb_SPFH_TGL_2_latlon.15x.15_{date}{run}",    
            f"CMC_glb_SPFH_TGL_40_latlon.15x.15_{date}{run}",
            f"CMC_glb_SPFH_TGL_80_latlon.15x.15_{date}{run}",
            f"CMC_glb_TCDC_SFC_0_latlon.15x.15_{date}{run}",
            f"CMC_glb_TMP_ISBL_1000_latlon.15x.15_{date}{run}", 
            f"CMC_glb_TMP_ISBL_100_latlon.15x.15_{date}{run}",
            f"CMC_glb_TMP_ISBL_1015_latlon.15x.15_{date}{run}", 
            f"CMC_glb_TMP_ISBL_10_latlon.15x.15_{date}{run}",
            f"CMC_glb_TMP_ISBL_150_latlon.15x.15_{date}{run}",
            f"CMC_glb_TMP_ISBL_175_latlon.15x.15_{date}{run}",
            f"CMC_glb_TMP_ISBL_1_latlon.15x.15_{date}{run}",
            f"CMC_glb_TMP_ISBL_200_latlon.15x.15_{date}{run}",
            f"CMC_glb_TMP_ISBL_20_latlon.15x.15_{date}{run}",
            f"CMC_glb_TMP_ISBL_225_latlon.15x.15_{date}{run}",
            f"CMC_glb_TMP_ISBL_250_latlon.15x.15_{date}{run}",
            f"CMC_glb_TMP_ISBL_275_latlon.15x.15_{date}{run}",
            f"CMC_glb_TMP_ISBL_300_latlon.15x.15_{date}{run}",
            f"CMC_glb_TMP_ISBL_30_latlon.15x.15_{date}{run}",
            f"CMC_glb_TMP_ISBL_350_latlon.15x.15_{date}{run}",
            f"CMC_glb_TMP_ISBL_400_latlon.15x.15_{date}{run}",
            f"CMC_glb_TMP_ISBL_450_latlon.15x.15_{date}{run}",
            f"CMC_glb_TMP_ISBL_500_latlon.15x.15_{date}{run}",
            f"CMC_glb_TMP_ISBL_50_latlon.15x.15_{date}{run}",
            f"CMC_glb_TMP_ISBL_550_latlon.15x.15_{date}{run}",
            f"CMC_glb_TMP_ISBL_5_latlon.15x.15_{date}{run}",
            f"CMC_glb_TMP_ISBL_600_latlon.15x.15_{date}{run}",
            f"CMC_glb_TMP_ISBL_650_latlon.15x.15_{date}{run}",
            f"CMC_glb_TMP_ISBL_700_latlon.15x.15_{date}{run}",
            f"CMC_glb_TMP_ISBL_750_latlon.15x.15_{date}{run}",
            f"CMC_glb_TMP_ISBL_800_latlon.15x.15_{date}{run}",  
            f"CMC_glb_TMP_ISBL_850_latlon.15x.15_{date}{run}",  
            f"CMC_glb_TMP_ISBL_875_latlon.15x.15_{date}{run}",  
            f"CMC_glb_TMP_ISBL_900_latlon.15x.15_{date}{run}",  
            f"CMC_glb_TMP_ISBL_925_latlon.15x.15_{date}{run}",  
            f"CMC_glb_TMP_ISBL_950_latlon.15x.15_{date}{run}",  
            f"CMC_glb_TMP_ISBL_970_latlon.15x.15_{date}{run}",  
            f"CMC_glb_TMP_ISBL_985_latlon.15x.15_{date}{run}",  
            f"CMC_glb_TMP_TGL_120_latlon.15x.15_{date}{run}",
            f"CMC_glb_TMP_TGL_2_latlon.15x.15_{date}{run}", 
            f"CMC_glb_TMP_TGL_40_latlon.15x.15_{date}{run}",
            f"CMC_glb_TMP_TGL_80_latlon.15x.15_{date}{run}",
            f"CMC_glb_TOTALX_SFC_0_latlon.15x.15_{date}{run}",
            f"CMC_glb_TSOIL_DBLL_100_latlon.15x.15_{date}{run}",
            f"CMC_glb_TSOIL_SFC_0_latlon.15x.15_{date}{run}",
            f"CMC_glb_UGRD_ISBL_1000_latlon.15x.15_{date}{run}",
            f"CMC_glb_UGRD_ISBL_100_latlon.15x.15_{date}{run}",
            f"CMC_glb_UGRD_ISBL_1015_latlon.15x.15_{date}{run}",
            f"CMC_glb_UGRD_ISBL_10_latlon.15x.15_{date}{run}",
            f"CMC_glb_UGRD_ISBL_150_latlon.15x.15_{date}{run}",
            f"CMC_glb_UGRD_ISBL_175_latlon.15x.15_{date}{run}",
            f"CMC_glb_UGRD_ISBL_1_latlon.15x.15_{date}{run}",
            f"CMC_glb_UGRD_ISBL_200_latlon.15x.15_{date}{run}",
            f"CMC_glb_UGRD_ISBL_20_latlon.15x.15_{date}{run}",
            f"CMC_glb_UGRD_ISBL_225_latlon.15x.15_{date}{run}",
            f"CMC_glb_UGRD_ISBL_250_latlon.15x.15_{date}{run}",
            f"CMC_glb_UGRD_ISBL_275_latlon.15x.15_{date}{run}",
            f"CMC_glb_UGRD_ISBL_300_latlon.15x.15_{date}{run}",
            f"CMC_glb_UGRD_ISBL_30_latlon.15x.15_{date}{run}",
            f"CMC_glb_UGRD_ISBL_350_latlon.15x.15_{date}{run}",
            f"CMC_glb_UGRD_ISBL_400_latlon.15x.15_{date}{run}",
            f"CMC_glb_UGRD_ISBL_450_latlon.15x.15_{date}{run}",
            f"CMC_glb_UGRD_ISBL_500_latlon.15x.15_{date}{run}", 
            f"CMC_glb_UGRD_ISBL_50_latlon.15x.15_{date}{run}",
            f"CMC_glb_UGRD_ISBL_550_latlon.15x.15_{date}{run}", 
            f"CMC_glb_UGRD_ISBL_5_latlon.15x.15_{date}{run}",
            f"CMC_glb_UGRD_ISBL_600_latlon.15x.15_{date}{run}", 
            f"CMC_glb_UGRD_ISBL_650_latlon.15x.15_{date}{run}", 
            f"CMC_glb_UGRD_ISBL_700_latlon.15x.15_{date}{run}", 
            f"CMC_glb_UGRD_ISBL_750_latlon.15x.15_{date}{run}",
            f"CMC_glb_UGRD_ISBL_800_latlon.15x.15_{date}{run}",
            f"CMC_glb_UGRD_ISBL_850_latlon.15x.15_{date}{run}",
            f"CMC_glb_UGRD_ISBL_875_latlon.15x.15_{date}{run}",
            f"CMC_glb_UGRD_ISBL_900_latlon.15x.15_{date}{run}",
            f"CMC_glb_UGRD_ISBL_925_latlon.15x.15_{date}{run}",
            f"CMC_glb_UGRD_ISBL_950_latlon.15x.15_{date}{run}",
            f"CMC_glb_UGRD_ISBL_970_latlon.15x.15_{date}{run}",
            f"CMC_glb_UGRD_ISBL_985_latlon.15x.15_{date}{run}",
            f"CMC_glb_UGRD_TGL_10_latlon.15x.15_{date}{run}",  
            f"CMC_glb_UGRD_TGL_120_latlon.15x.15_{date}{run}",
            f"CMC_glb_UGRD_TGL_40_latlon.15x.15_{date}{run}",
            f"CMC_glb_UGRD_TGL_80_latlon.15x.15_{date}{run}",
            f"CMC_glb_ULWRF_NTAT_0_latlon.15x.15_{date}{run}",
            f"CMC_glb_UVIndexClearSky_Sfc_latlon.15x.15_{date}{run}",
            f"CMC_glb_UVIndex_Sfc_latlon.15x.15_{date}{run}",
            f"CMC_glb_VGRD_ISBL_1000_latlon.15x.15_{date}{run}",
            f"CMC_glb_VGRD_ISBL_100_latlon.15x.15_{date}{run}",
            f"CMC_glb_VGRD_ISBL_1015_latlon.15x.15_{date}{run}",
            f"CMC_glb_VGRD_ISBL_10_latlon.15x.15_{date}{run}",
            f"CMC_glb_VGRD_ISBL_150_latlon.15x.15_{date}{run}",
            f"CMC_glb_VGRD_ISBL_175_latlon.15x.15_{date}{run}",
            f"CMC_glb_VGRD_ISBL_1_latlon.15x.15_{date}{run}",
            f"CMC_glb_VGRD_ISBL_200_latlon.15x.15_{date}{run}",
            f"CMC_glb_VGRD_ISBL_20_latlon.15x.15_{date}{run}",
            f"CMC_glb_VGRD_ISBL_225_latlon.15x.15_{date}{run}",
            f"CMC_glb_VGRD_ISBL_250_latlon.15x.15_{date}{run}",
            f"CMC_glb_VGRD_ISBL_275_latlon.15x.15_{date}{run}",
            f"CMC_glb_VGRD_ISBL_300_latlon.15x.15_{date}{run}",
            f"CMC_glb_VGRD_ISBL_30_latlon.15x.15_{date}{run}",
            f"CMC_glb_VGRD_ISBL_350_latlon.15x.15_{date}{run}",
            f"CMC_glb_VGRD_ISBL_400_latlon.15x.15_{date}{run}",
            f"CMC_glb_VGRD_ISBL_450_latlon.15x.15_{date}{run}",
            f"CMC_glb_VGRD_ISBL_500_latlon.15x.15_{date}{run}", 
            f"CMC_glb_VGRD_ISBL_50_latlon.15x.15_{date}{run}",
            f"CMC_glb_VGRD_ISBL_550_latlon.15x.15_{date}{run}", 
            f"CMC_glb_VGRD_ISBL_5_latlon.15x.15_{date}{run}",
            f"CMC_glb_VGRD_ISBL_600_latlon.15x.15_{date}{run}", 
            f"CMC_glb_VGRD_ISBL_650_latlon.15x.15_{date}{run}", 
            f"CMC_glb_VGRD_ISBL_700_latlon.15x.15_{date}{run}", 
            f"CMC_glb_VGRD_ISBL_750_latlon.15x.15_{date}{run}",
            f"CMC_glb_VGRD_ISBL_800_latlon.15x.15_{date}{run}",
            f"CMC_glb_VGRD_ISBL_850_latlon.15x.15_{date}{run}",
            f"CMC_glb_VGRD_ISBL_875_latlon.15x.15_{date}{run}",
            f"CMC_glb_VGRD_ISBL_900_latlon.15x.15_{date}{run}",
            f"CMC_glb_VGRD_ISBL_925_latlon.15x.15_{date}{run}",
            f"CMC_glb_VGRD_ISBL_950_latlon.15x.15_{date}{run}",
            f"CMC_glb_VGRD_ISBL_970_latlon.15x.15_{date}{run}",
            f"CMC_glb_VGRD_ISBL_985_latlon.15x.15_{date}{run}",
            f"CMC_glb_VGRD_TGL_10_latlon.15x.15_{date}{run}",  
            f"CMC_glb_VGRD_TGL_120_latlon.15x.15_{date}{run}",
            f"CMC_glb_VGRD_TGL_40_latlon.15x.15_{date}{run}",
            f"CMC_glb_VGRD_TGL_80_latlon.15x.15_{date}{run}",
            f"CMC_glb_VVEL_ISBL_200_latlon.15x.15_{date}{run}", 
            f"CMC_glb_VVEL_ISBL_250_latlon.15x.15_{date}{run}",
            f"CMC_glb_VVEL_ISBL_500_latlon.15x.15_{date}{run}",
            f"CMC_glb_VVEL_ISBL_600_latlon.15x.15_{date}{run}",
            f"CMC_glb_VVEL_ISBL_700_latlon.15x.15_{date}{run}", 
            f"CMC_glb_VVEL_ISBL_850_latlon.15x.15_{date}{run}",
            f"CMC_glb_WCHIL_SFC_0_latlon.15x.15_{date}{run}",
            f"CMC_glb_WDIR_ISBL_1000_latlon.15x.15_{date}{run}",
            f"CMC_glb_WDIR_ISBL_100_latlon.15x.15_{date}{run}",
            f"CMC_glb_WDIR_ISBL_1015_latlon.15x.15_{date}{run}",
            f"CMC_glb_WDIR_ISBL_10_latlon.15x.15_{date}{run}",
            f"CMC_glb_WDIR_ISBL_150_latlon.15x.15_{date}{run}",
            f"CMC_glb_WDIR_ISBL_175_latlon.15x.15_{date}{run}",
            f"CMC_glb_WDIR_ISBL_1_latlon.15x.15_{date}{run}",
            f"CMC_glb_WDIR_ISBL_200_latlon.15x.15_{date}{run}", 
            f"CMC_glb_WDIR_ISBL_20_latlon.15x.15_{date}{run}",
            f"CMC_glb_WDIR_ISBL_225_latlon.15x.15_{date}{run}", 
            f"CMC_glb_WDIR_ISBL_250_latlon.15x.15_{date}{run}", 
            f"CMC_glb_WDIR_ISBL_275_latlon.15x.15_{date}{run}", 
            f"CMC_glb_WDIR_ISBL_300_latlon.15x.15_{date}{run}", 
            f"CMC_glb_WDIR_ISBL_30_latlon.15x.15_{date}{run}",
            f"CMC_glb_WDIR_ISBL_350_latlon.15x.15_{date}{run}", 
            f"CMC_glb_WDIR_ISBL_400_latlon.15x.15_{date}{run}", 
            f"CMC_glb_WDIR_ISBL_450_latlon.15x.15_{date}{run}",
            f"CMC_glb_WDIR_ISBL_500_latlon.15x.15_{date}{run}",
            f"CMC_glb_WDIR_ISBL_50_latlon.15x.15_{date}{run}",
            f"CMC_glb_WDIR_ISBL_550_latlon.15x.15_{date}{run}",
            f"CMC_glb_WDIR_ISBL_5_latlon.15x.15_{date}{run}",
            f"CMC_glb_WDIR_ISBL_600_latlon.15x.15_{date}{run}",
            f"CMC_glb_WDIR_ISBL_650_latlon.15x.15_{date}{run}",
            f"CMC_glb_WDIR_ISBL_700_latlon.15x.15_{date}{run}",
            f"CMC_glb_WDIR_ISBL_750_latlon.15x.15_{date}{run}",
            f"CMC_glb_WDIR_ISBL_800_latlon.15x.15_{date}{run}",
            f"CMC_glb_WDIR_ISBL_850_latlon.15x.15_{date}{run}",
            f"CMC_glb_WDIR_ISBL_875_latlon.15x.15_{date}{run}",
            f"CMC_glb_WDIR_ISBL_900_latlon.15x.15_{date}{run}",
            f"CMC_glb_WDIR_ISBL_925_latlon.15x.15_{date}{run}",
            f"CMC_glb_WDIR_ISBL_950_latlon.15x.15_{date}{run}",
            f"CMC_glb_WDIR_ISBL_970_latlon.15x.15_{date}{run}",
            f"CMC_glb_WDIR_ISBL_985_latlon.15x.15_{date}{run}",
            f"CMC_glb_WDIR_TGL_10_latlon.15x.15_{date}{run}",  
            f"CMC_glb_WDIR_TGL_120_latlon.15x.15_{date}{run}", 
            f"CMC_glb_WDIR_TGL_40_latlon.15x.15_{date}{run}",
            f"CMC_glb_WDIR_TGL_80_latlon.15x.15_{date}{run}",  
            f"CMC_glb_WIND_ISBL_1000_latlon.15x.15_{date}{run}",
            f"CMC_glb_WIND_ISBL_100_latlon.15x.15_{date}{run}",
            f"CMC_glb_WIND_ISBL_1015_latlon.15x.15_{date}{run}",
            f"CMC_glb_WIND_ISBL_10_latlon.15x.15_{date}{run}",
            f"CMC_glb_WIND_ISBL_150_latlon.15x.15_{date}{run}",
            f"CMC_glb_WIND_ISBL_175_latlon.15x.15_{date}{run}",
            f"CMC_glb_WIND_ISBL_1_latlon.15x.15_{date}{run}",
            f"CMC_glb_WIND_ISBL_200_latlon.15x.15_{date}{run}", 
            f"CMC_glb_WIND_ISBL_20_latlon.15x.15_{date}{run}",
            f"CMC_glb_WIND_ISBL_225_latlon.15x.15_{date}{run}", 
            f"CMC_glb_WIND_ISBL_250_latlon.15x.15_{date}{run}", 
            f"CMC_glb_WIND_ISBL_275_latlon.15x.15_{date}{run}", 
            f"CMC_glb_WIND_ISBL_300_latlon.15x.15_{date}{run}", 
            f"CMC_glb_WIND_ISBL_30_latlon.15x.15_{date}{run}",
            f"CMC_glb_WIND_ISBL_350_latlon.15x.15_{date}{run}", 
            f"CMC_glb_WIND_ISBL_400_latlon.15x.15_{date}{run}", 
            f"CMC_glb_WIND_ISBL_450_latlon.15x.15_{date}{run}", 
            f"CMC_glb_WIND_ISBL_500_latlon.15x.15_{date}{run}", 
            f"CMC_glb_WIND_ISBL_50_latlon.15x.15_{date}{run}",
            f"CMC_glb_WIND_ISBL_550_latlon.15x.15_{date}{run}", 
            f"CMC_glb_WIND_ISBL_5_latlon.15x.15_{date}{run}",
            f"CMC_glb_WIND_ISBL_600_latlon.15x.15_{date}{run}", 
            f"CMC_glb_WIND_ISBL_650_latlon.15x.15_{date}{run}", 
            f"CMC_glb_WIND_ISBL_700_latlon.15x.15_{date}{run}", 
            f"CMC_glb_WIND_ISBL_750_latlon.15x.15_{date}{run}",
            f"CMC_glb_WIND_ISBL_800_latlon.15x.15_{date}{run}",
            f"CMC_glb_WIND_ISBL_850_latlon.15x.15_{date}{run}",
            f"CMC_glb_WIND_ISBL_875_latlon.15x.15_{date}{run}", 
            f"CMC_glb_WIND_ISBL_900_latlon.15x.15_{date}{run}", 
            f"CMC_glb_WIND_ISBL_925_latlon.15x.15_{date}{run}", 
            f"CMC_glb_WIND_ISBL_950_latlon.15x.15_{date}{run}", 
            f"CMC_glb_WIND_ISBL_970_latlon.15x.15_{date}{run}",
            f"CMC_glb_WIND_ISBL_985_latlon.15x.15_{date}{run}",
            f"CMC_glb_WIND_TGL_10_latlon.15x.15_{date}{run}",
            f"CMC_glb_WIND_TGL_120_latlon.15x.15_{date}{run}",
            f"CMC_glb_WIND_TGL_40_latlon.15x.15_{date}{run}",   
            f"CMC_glb_WIND_TGL_80_latlon.15x.15_{date}{run}"
            
        ]
    
    return file_prefixes


def parameter_list(set):
    
    """
    This function returns a parameter list for the GEM Global
    
    Required Arguments: 
    
    1) set (String) - The set of parameters. 
    
    Sets of Parameters
    ------------------
    
    Note: If set='full' the process can take a while given the large amount of data needed to be downloaded and processed. 
    
    Optional Arguments: None
    
    Returns
    -------
    
    A parameter list for the GEM Global    
    """
    
    set = set.lower()
    
    if set == 'full':
        
        parameters = [
        
            f"ABSV_ISBL_200",
            f"ABSV_ISBL_250",
            f"ABSV_ISBL_500",
            f"ABSV_ISBL_700",
            f"ABSV_ISBL_850",
            f"ACPCP_SFC_0",
            f"ALBDO_SFC_0",
            f"CAPE_SFC_0",
            f"CIN_SFC_0",
            f"CWAT_EATM_0",
            f"DEPR_ISBL_1000",
            f"DEPR_ISBL_100",
            f"DEPR_ISBL_1015",
            f"DEPR_ISBL_10",
            f"DEPR_ISBL_150",
            f"DEPR_ISBL_175",
            f"DEPR_ISBL_200",
            f"DEPR_ISBL_20",
            f"DEPR_ISBL_225",
            f"DEPR_ISBL_250",
            f"DEPR_ISBL_275",
            f"DEPR_ISBL_300",
            f"DEPR_ISBL_30",
            f"DEPR_ISBL_350",
            f"DEPR_ISBL_400",
            f"DEPR_ISBL_450",
            f"DEPR_ISBL_500",
            f"DEPR_ISBL_50",
            f"DEPR_ISBL_550",
            f"DEPR_ISBL_600",
            f"DEPR_ISBL_650",
            f"DEPR_ISBL_700",
            f"DEPR_ISBL_750",
            f"DEPR_ISBL_800",
            f"DEPR_ISBL_850",
            f"DEPR_ISBL_875",
            f"DEPR_ISBL_900",
            f"DEPR_ISBL_925",
            f"DEPR_ISBL_950",
            f"DEPR_ISBL_970",
            f"DEPR_ISBL_985",
            f"DEPR_TGL_2",
            f"DLWRF_SFC_0",
            f"DPT_TGL_2",
            f"DSWRF_NTAT_0",
            f"DSWRF_SFC_0",
            f"GUST_MAX_TGL_10",
            f"GUST_MIN_TGL_10",
            f"GUST_TGL_10",
            f"HGT_ISBL_1000",
            f"HGT_ISBL_100",
            f"HGT_ISBL_1015",
            f"HGT_ISBL_10",
            f"HGT_ISBL_150",
            f"HGT_ISBL_175",
            f"HGT_ISBL_1",
            f"HGT_ISBL_200",
            f"HGT_ISBL_20",
            f"HGT_ISBL_225",
            f"HGT_ISBL_250",
            f"HGT_ISBL_275",
            f"HGT_ISBL_300",
            f"HGT_ISBL_30",
            f"HGT_ISBL_350",
            f"HGT_ISBL_400",
            f"HGT_ISBL_450",
            f"HGT_ISBL_500",
            f"HGT_ISBL_50",
            f"HGT_ISBL_550",
            f"HGT_ISBL_5",
            f"HGT_ISBL_600",
            f"HGT_ISBL_650",
            f"HGT_ISBL_700",
            f"HGT_ISBL_750",
            f"HGT_ISBL_800",
            f"HGT_ISBL_850",
            f"HGT_ISBL_875",
            f"HGT_ISBL_900",
            f"HGT_ISBL_925",
            f"HGT_ISBL_950",
            f"HGT_ISBL_970",
            f"HGT_ISBL_985",
            f"HGT_ISBY_1000-500",
            f"HGT_ISBY_1000-850",
            f"HGT_ISBY_850-700",
            f"HPBL_SFC_0",
            f"Humidex_SFC_0",
            f"KX_SFC_0",
            f"LHTFL_SFC_0",
            f"MU-VT-LI_ISBL_500",
            f"NLWRS_SFC_0",
            f"NSWRS_SFC_0",
            f"O3MixingRatio_Sfc",
            f"O3_EAtm",
            f"PRES_PVU_1.5",
            f"PRES_PVU_1",
            f"PRES_PVU_2",
            f"PRES_SFC_0",
            f"PRMSL_MSL_0",
            f"PTYPE_SFC_0",
            f"RELV_ISBL_200",
            f"RELV_ISBL_250",
            f"RELV_ISBL_500",
            f"RELV_ISBL_700",
            f"RELV_ISBL_850",
            f"RH_ISBL_1000",
            f"RH_ISBL_100",
            f"RH_ISBL_1015",
            f"RH_ISBL_10",
            f"RH_ISBL_150",
            f"RH_ISBL_175",
            f"RH_ISBL_200",
            f"RH_ISBL_20",
            f"RH_ISBL_225",
            f"RH_ISBL_250",
            f"RH_ISBL_275",
            f"RH_ISBL_300",
            f"RH_ISBL_30",
            f"RH_ISBL_350",
            f"RH_ISBL_400",
            f"RH_ISBL_450",
            f"RH_ISBL_500",
            f"RH_ISBL_50",
            f"RH_ISBL_550",
            f"RH_ISBL_600",
            f"RH_ISBL_650",
            f"RH_ISBL_700",
            f"RH_ISBL_750",   
            f"RH_ISBL_800",   
            f"RH_ISBL_850",
            f"RH_ISBL_875",
            f"RH_ISBL_900",   
            f"RH_ISBL_925",   
            f"RH_ISBL_950",   
            f"RH_ISBL_970",
            f"RH_ISBL_985",
            f"RH_TGL_2",  
            f"SDEN_SFC_0",
            f"SFCWRO_SFC_0",
            f"SHTFL_SFC_0",
            f"SHWINX_ISBL_500",
            f"SKINT_SFC_0",
            f"SNOD_SFC_0",
            f"SOILVIC_SFC_0",
            f"SOILW_DBLL_100",
            f"SOILW_DBLY_10",
            f"SPFH_ISBL_1000",
            f"SPFH_ISBL_100",
            f"SPFH_ISBL_1015",
            f"SPFH_ISBL_10",  
            f"SPFH_ISBL_150",
            f"SPFH_ISBL_175",
            f"SPFH_ISBL_1",   
            f"SPFH_ISBL_200",
            f"SPFH_ISBL_20",  
            f"SPFH_ISBL_225",
            f"SPFH_ISBL_250", 
            f"SPFH_ISBL_275",
            f"SPFH_ISBL_300", 
            f"SPFH_ISBL_30",  
            f"SPFH_ISBL_350", 
            f"SPFH_ISBL_400",
            f"SPFH_ISBL_450", 
            f"SPFH_ISBL_500",
            f"SPFH_ISBL_50",  
            f"SPFH_ISBL_550",
            f"SPFH_ISBL_5",
            f"SPFH_ISBL_600",
            f"SPFH_ISBL_650",
            f"SPFH_ISBL_700",
            f"SPFH_ISBL_750",
            f"SPFH_ISBL_800", 
            f"SPFH_ISBL_850",
            f"SPFH_ISBL_875",
            f"SPFH_ISBL_900",
            f"SPFH_ISBL_925",
            f"SPFH_ISBL_950",
            f"SPFH_ISBL_970",
            f"SPFH_ISBL_985",
            f"SPFH_SFC_0",
            f"SPFH_TGL_120",  
            f"SPFH_TGL_2",    
            f"SPFH_TGL_40",
            f"SPFH_TGL_80",
            f"TCDC_SFC_0",
            f"TMP_ISBL_1000", 
            f"TMP_ISBL_100",
            f"TMP_ISBL_1015", 
            f"TMP_ISBL_10",
            f"TMP_ISBL_150",
            f"TMP_ISBL_175",
            f"TMP_ISBL_1",
            f"TMP_ISBL_200",
            f"TMP_ISBL_20",
            f"TMP_ISBL_225",
            f"TMP_ISBL_250",
            f"TMP_ISBL_275",
            f"TMP_ISBL_300",
            f"TMP_ISBL_30",
            f"TMP_ISBL_350",
            f"TMP_ISBL_400",
            f"TMP_ISBL_450",
            f"TMP_ISBL_500",
            f"TMP_ISBL_50",
            f"TMP_ISBL_550",
            f"TMP_ISBL_5",
            f"TMP_ISBL_600",
            f"TMP_ISBL_650",
            f"TMP_ISBL_700",
            f"TMP_ISBL_750",
            f"TMP_ISBL_800",  
            f"TMP_ISBL_850",  
            f"TMP_ISBL_875",  
            f"TMP_ISBL_900",  
            f"TMP_ISBL_925",  
            f"TMP_ISBL_950",  
            f"TMP_ISBL_970",  
            f"TMP_ISBL_985",  
            f"TMP_TGL_120",
            f"TMP_TGL_2", 
            f"TMP_TGL_40",
            f"TMP_TGL_80",
            f"TOTALX_SFC_0",
            f"TSOIL_DBLL_100",
            f"TSOIL_SFC_0",
            f"UGRD_ISBL_1000",
            f"UGRD_ISBL_100",
            f"UGRD_ISBL_1015",
            f"UGRD_ISBL_10",
            f"UGRD_ISBL_150",
            f"UGRD_ISBL_175",
            f"UGRD_ISBL_1",
            f"UGRD_ISBL_200",
            f"UGRD_ISBL_20",
            f"UGRD_ISBL_225",
            f"UGRD_ISBL_250",
            f"UGRD_ISBL_275",
            f"UGRD_ISBL_300",
            f"UGRD_ISBL_30",
            f"UGRD_ISBL_350",
            f"UGRD_ISBL_400",
            f"UGRD_ISBL_450",
            f"UGRD_ISBL_500", 
            f"UGRD_ISBL_50",
            f"UGRD_ISBL_550", 
            f"UGRD_ISBL_5",
            f"UGRD_ISBL_600", 
            f"UGRD_ISBL_650", 
            f"UGRD_ISBL_700", 
            f"UGRD_ISBL_750",
            f"UGRD_ISBL_800",
            f"UGRD_ISBL_850",
            f"UGRD_ISBL_875",
            f"UGRD_ISBL_900",
            f"UGRD_ISBL_925",
            f"UGRD_ISBL_950",
            f"UGRD_ISBL_970",
            f"UGRD_ISBL_985",
            f"UGRD_TGL_10",  
            f"UGRD_TGL_120",
            f"UGRD_TGL_40",
            f"UGRD_TGL_80",
            f"ULWRF_NTAT_0",
            f"UVIndexClearSky_Sfc",
            f"UVIndex_Sfc",
            f"VGRD_ISBL_1000",
            f"VGRD_ISBL_100",
            f"VGRD_ISBL_1015",
            f"VGRD_ISBL_10",
            f"VGRD_ISBL_150",
            f"VGRD_ISBL_175",
            f"VGRD_ISBL_1",
            f"VGRD_ISBL_200",
            f"VGRD_ISBL_20",
            f"VGRD_ISBL_225",
            f"VGRD_ISBL_250",
            f"VGRD_ISBL_275",
            f"VGRD_ISBL_300",
            f"VGRD_ISBL_30",
            f"VGRD_ISBL_350",
            f"VGRD_ISBL_400",
            f"VGRD_ISBL_450",
            f"VGRD_ISBL_500", 
            f"VGRD_ISBL_50",
            f"VGRD_ISBL_550", 
            f"VGRD_ISBL_5",
            f"VGRD_ISBL_600", 
            f"VGRD_ISBL_650", 
            f"VGRD_ISBL_700", 
            f"VGRD_ISBL_750",
            f"VGRD_ISBL_800",
            f"VGRD_ISBL_850",
            f"VGRD_ISBL_875",
            f"VGRD_ISBL_900",
            f"VGRD_ISBL_925",
            f"VGRD_ISBL_950",
            f"VGRD_ISBL_970",
            f"VGRD_ISBL_985",
            f"VGRD_TGL_10",  
            f"VGRD_TGL_120",
            f"VGRD_TGL_40",
            f"VGRD_TGL_80",
            f"VVEL_ISBL_200", 
            f"VVEL_ISBL_250",
            f"VVEL_ISBL_500",
            f"VVEL_ISBL_600",
            f"VVEL_ISBL_700", 
            f"VVEL_ISBL_850",
            f"WCHIL_SFC_0",
            f"WDIR_ISBL_1000",
            f"WDIR_ISBL_100",
            f"WDIR_ISBL_1015",
            f"WDIR_ISBL_10",
            f"WDIR_ISBL_150",
            f"WDIR_ISBL_175",
            f"WDIR_ISBL_1",
            f"WDIR_ISBL_200", 
            f"WDIR_ISBL_20",
            f"WDIR_ISBL_225", 
            f"WDIR_ISBL_250", 
            f"WDIR_ISBL_275", 
            f"WDIR_ISBL_300", 
            f"WDIR_ISBL_30",
            f"WDIR_ISBL_350", 
            f"WDIR_ISBL_400", 
            f"WDIR_ISBL_450",
            f"WDIR_ISBL_500",
            f"WDIR_ISBL_50",
            f"WDIR_ISBL_550",
            f"WDIR_ISBL_5",
            f"WDIR_ISBL_600",
            f"WDIR_ISBL_650",
            f"WDIR_ISBL_700",
            f"WDIR_ISBL_750",
            f"WDIR_ISBL_800",
            f"WDIR_ISBL_850",
            f"WDIR_ISBL_875",
            f"WDIR_ISBL_900",
            f"WDIR_ISBL_925",
            f"WDIR_ISBL_950",
            f"WDIR_ISBL_970",
            f"WDIR_ISBL_985",
            f"WDIR_TGL_10",  
            f"WDIR_TGL_120", 
            f"WDIR_TGL_40",
            f"WDIR_TGL_80",  
            f"WIND_ISBL_1000",
            f"WIND_ISBL_100",
            f"WIND_ISBL_1015",
            f"WIND_ISBL_10",
            f"WIND_ISBL_150",
            f"WIND_ISBL_175",
            f"WIND_ISBL_1",
            f"WIND_ISBL_200", 
            f"WIND_ISBL_20",
            f"WIND_ISBL_225", 
            f"WIND_ISBL_250", 
            f"WIND_ISBL_275", 
            f"WIND_ISBL_300", 
            f"WIND_ISBL_30",
            f"WIND_ISBL_350", 
            f"WIND_ISBL_400", 
            f"WIND_ISBL_450", 
            f"WIND_ISBL_500", 
            f"WIND_ISBL_50",
            f"WIND_ISBL_550", 
            f"WIND_ISBL_5",
            f"WIND_ISBL_600", 
            f"WIND_ISBL_650", 
            f"WIND_ISBL_700", 
            f"WIND_ISBL_750",
            f"WIND_ISBL_800",
            f"WIND_ISBL_850",
            f"WIND_ISBL_875", 
            f"WIND_ISBL_900", 
            f"WIND_ISBL_925", 
            f"WIND_ISBL_950", 
            f"WIND_ISBL_970",
            f"WIND_ISBL_985",
            f"WIND_TGL_10",
            f"WIND_TGL_120",
            f"WIND_TGL_40",   
            f"WIND_TGL_80"
            
        ]
        
    elif set == 'dynamics':
        
         parameters = [
        
            f"ABSV_ISBL_200",
            f"ABSV_ISBL_250",
            f"ABSV_ISBL_500",
            f"ABSV_ISBL_700",
            f"ABSV_ISBL_850"
            
         ]
         
    elif set == 'convective':
        
        parameters = [
            
            f"ACPCP_SFC_0",
            f"CAPE_SFC_0",
            f"CIN_SFC_0",
            
        ]       
    
    return parameters


def build_gem_global_directory(set):
    """
    This function builds the file directory for all of the GEM Global Data Files. 
    
    Required Arguments: None
    
    Optional Arguments: None
    
    Returns
    -------
    
    Builds the file structure for the GEM Global Data Files    
    """
    
    parameters = parameter_list(set)
    
    if os.path.exists(f"GEM GLOBAL"):
        pass
    else:
        os.mkdir(f"GEM GLOBAL")
        
    for p in parameters:
        if os.path.exists(f"GEM GLOBAL/{p}"):
            pass
        else:
            os.mkdir(f"GEM GLOBAL/{p}")
        
    